### ISSUE TITLE
Random Test Failure

### ISSUE THREAD

**Issue by juanpedromoreno** [scala-exercises/exercises-scalatutorial#10]
It seems like with latest merge now we have random test failures related to `check rational ordering`.

https://travis-ci.org/scala-exercises/exercises-scalatutorial/builds/216055586

Most of the times it's happening here:

https://github.com/scala-exercises/exercises-scalatutorial/blob/master/src/test/scala/scalatutorial/sections/TypeClassesSpec.scala#L18-L22

**Comment by julienrf** [comment]
Failures are happening when functions are arbitrarily generated by scalacheck. In the current version, we rely on scalacheck generating *constant functions*. It can happen that such a generated function sometimes passes the test. So, my guess is that the test fails because randomly generated solutions which are expected to be wrong are not.
